# FZF Color Configuration
# Generated by matugen to match terminal theme colors

# FZF color scheme using matugen colors
export FZF_DEFAULT_OPTS="
--color=bg+:{{colors.surface_container.default.hex}}
--color=bg:{{colors.surface.default.hex}}
--color=spinner:{{colors.primary.default.hex}}
--color=hl:{{colors.primary.default.hex}}
--color=fg:{{colors.on_surface.default.hex}}
--color=header:{{colors.primary.default.hex}}
--color=info:{{colors.secondary.default.hex}}
--color=pointer:{{colors.primary.default.hex}}
--color=marker:{{colors.primary.default.hex}}
--color=fg+:{{colors.on_surface.default.hex}}
--color=prompt:{{colors.primary.default.hex}}
--color=hl+:{{colors.primary.default.hex}}
--color=border:{{colors.outline.default.hex}}
--height=40%
--layout=reverse
--border=rounded
--inline-info
--preview-window=right:50%:wrap
--bind='ctrl-u:preview-page-up,ctrl-d:preview-page-down'
--bind='ctrl-f:page-down,ctrl-b:page-up'
--bind='alt-a:select-all,alt-d:deselect-all'
--bind='ctrl-/:toggle-preview'
"

# FZF command configurations with theme colors
export FZF_DEFAULT_COMMAND='fd --type f --hidden --follow --exclude .git --color=always'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export FZF_ALT_C_COMMAND='fd --type d --hidden --follow --exclude .git --color=always'

# FZF preview commands with syntax highlighting
export FZF_CTRL_T_OPTS="
--preview 'bat --color=always --style=numbers --line-range=:500 {}'
--preview-window 'right:50%:wrap'
"

export FZF_ALT_C_OPTS="
--preview 'tree -C {} | head -200'
--preview-window 'right:50%:wrap'
"

# FZF completion trigger
export FZF_COMPLETION_TRIGGER='**'

# FZF completion options
export FZF_COMPLETION_OPTS="
--border
--info=inline
--color=bg+:{{colors.surface_container.default.hex}}
--color=bg:{{colors.surface.default.hex}}
--color=hl:{{colors.primary.default.hex}}
--color=fg:{{colors.on_surface.default.hex}}
--color=pointer:{{colors.primary.default.hex}}
--color=marker:{{colors.primary.default.hex}}
--color=fg+:{{colors.on_surface.default.hex}}
--color=prompt:{{colors.primary.default.hex}}
--color=hl+:{{colors.primary.default.hex}}
"

# Custom FZF functions with theme integration
fzf_git_log() {
    git log --color=always --format="%C(auto)%h%d %s %C(black)%C(bold)%cr" "$@" |
    fzf --ansi --no-sort --reverse --tiebreak=index \
        --preview "f() { set -- \$(echo -- \"\$@\" | grep -o '[a-f0-9]\{7\}'); [ \$# -eq 0 ] || git show --color=always \$1; }; f {}" \
        --bind "ctrl-m:execute: (grep -o '[a-f0-9]\{7\}' | head -1 | xargs -I % sh -c 'git show --color=always %') << 'FZF-EOF'
{}
FZF-EOF"
}

fzf_git_branch() {
    git branch -a --color=always | grep -v '/HEAD\s' | sort |
    fzf --ansi --multi --tac --preview-window right:70% \
        --preview 'git log --oneline --graph --date=short --color=always --pretty="format:%C(auto)%cd %h%d %s" $(sed s/^..// <<< {} | cut -d" " -f1) | head -'$LINES |
    sed 's/^..//' | cut -d' ' -f1 |
    sed 's#^remotes/##'
}

# Aliases for FZF functions
alias fgl='fzf_git_log'
alias fgb='fzf_git_branch'
