[config.wallpaper]
set = false
command = "swww"

[templates.hyprland]
input_path = "~/.config/matugen/templates/hyprland-colors.conf"
output_path = "~/.config/hypr/colors/colors.conf"

[templates.kitty]
input_path = "~/.config/matugen/templates/kitty-colors.conf"
output_path = "~/.config/kitty/colors.conf"

[templates.gtk3]
input_path = "~/.config/matugen/templates/gtk-theme.css"
output_path = "~/.themes/MatugenDynamic/gtk-3.0/gtk.css"

[templates.gtk4]
input_path = "~/.config/matugen/templates/gtk-theme.css"
output_path = "~/.themes/MatugenDynamic/gtk-4.0/gtk.css"

[templates.qt5]
input_path = "~/.config/matugen/templates/qt-colors.conf"
output_path = "~/.config/qt5ct/colors/matugen-dynamic.conf"

[templates.qt6]
input_path = "~/.config/matugen/templates/qt-colors.conf"
output_path = "~/.config/qt6ct/colors/matugen-dynamic.conf"

[templates.swaync]
input_path = "~/.config/matugen/templates/swaync-colors.css"
output_path = "~/.config/swaync/colors.css"

[templates.starship]
input_path = "~/.config/matugen/templates/starship-colors.toml"
output_path = "~/.config/starship.toml"

[templates.tmux]
input_path = "~/.config/matugen/templates/tmux-colors.conf"
output_path = "~/.config/tmux/tmux.conf"

[templates.btop]
input_path = "~/.config/matugen/templates/btop.theme"
output_path = "~/.config/btop/themes/matugen.theme"

[templates.fzf]
input_path = "~/.config/matugen/templates/fzf-colors.sh"
output_path = "~/.config/fzf/colors.sh"

[templates.fastfetch]
input_path = "~/.config/matugen/templates/fastfetch-config.jsonc"
output_path = "~/.config/fastfetch/config.jsonc"

[templates.hyprlock]
input_path = "~/.config/matugen/templates/hyprlock.conf"
output_path = "~/.config/hypr/hyprlock.conf"