# SWWW Configuration
# This file configures SWWW for optimal wallpaper management

[daemon]
# Daemon settings
log_level = "info"
max_history = 20

[image]
# Image processing settings
resize = "fit"  # fit, fill, stretch, center, tile
filter = "Lanczos3"  # Nearest, Linear, Cubic, Lanczos3

[transition]
# Transition settings
type = "wipe"  # simple, fade, left, right, top, bottom, wipe, grow, outer, wave
duration = 1.0
angle = 0.0  # For wipe transitions
pos = "center"  # For wipe transitions
bezier = "0.4,0.0,0.2,1.0"  # For smooth transitions
step = 20  # For wave transitions

[output]
# Output settings
priority = "output"  # output, workspace
