#!/usr/bin/env bash
# Use terminal pinentry when signing from a TTY; GUI pinentry otherwise.

if [[ -n "${GPG_TTY:-}" && -t 0 && -t 1 ]]; then
  exec /usr/bin/pinentry-curses "$@"
fi

if [[ -n "${WAYLAND_DISPLAY:-}" ]]; then
  exec /usr/bin/pinentry-qt "$@"
fi

if [[ -n "${DISPLAY:-}" ]]; then
  exec /usr/bin/pinentry-gnome3 "$@"
fi

exec /usr/bin/pinentry-curses "$@"
